# Generated by Django 4.1.1 on 2022-09-08 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0010_merge_20220903_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='customer_username',
            field=models.OneToOneField(blank=True, default=models.AutoField(primary_key=True, serialize=False), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
